apiVersion: v1
kind: Template

labels:
  application: demo4-leaderboard-server

metadata:
  name: demo4-leaderboard-server

parameters:
  - name: APPLICATION_NAME
    value: demo4-leaderboard-server
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: PORT
    value: "8080"
    required: true
  - name: IP
    value: "0.0.0.0"
    required: true
  - name: IMAGE_REPOSITORY
    value: quay.io/redhatdemo/demo4-leaderboard-server:latest
    required: true
  - name: DATAGRID_HOST
    value: datagrid-service.datagrid-demo.svc.cluster.local
    required: true
  - name: DATAGRID_HOTROD_PORT
    value: "11222"
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${APPLICATION_NAME}
    data:
    stringData:
      DATAGRID_HOST: ${DATAGRID_HOST}
      DATAGRID_HOTROD_PORT: ${DATAGRID_HOTROD_PORT}

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      replicas: ${REPLICAS}
      selector:
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          containers:
            - env:
                - name: IP
                  value: "${IP}"
                - name: PORT
                  value: "${PORT}"
              envFrom:
                - secretRef:
                    name: ${APPLICATION_NAME}
              image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APPLICATION_NAME}
